imageFileNames = {'C:\Users\kenansun\Documents\MATLAB\First Try\0.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\1_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\2_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\3_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\4_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\5_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\6_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\7_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\8_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\9_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\10_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\11_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\12_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\13_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\14_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\15_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\16_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\17_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\18_.bmp',...
  'C:\Users\kenansun\Documents\MATLAB\First Try\19_.bmp',...
  };

load('calibrationSession_firt_try.mat')

for i=1:1:20
  originalImage = imread(imageFileNames{i});
  undistortedImage = undistortImage(originalImage, ...
    calibrationSession.CameraParameters);
    
  imagename = sprintf('%s\\First Try\\sheetLight_%02d.bmp',pwd,i);
  imwrite(undistortedImage, imagename);
end